### ISSUE TITLE
error when trying to scroll to an inexistant anchor

### ISSUE THREAD

**Issue by sinsunsan** [oblador/angular-scroll#101]
I have an anchor 
https://www.wecook.fr/planning#!/dsdssdsd#lkjklj
in the context of an angular page, that does not exist #lkjklj does not exist in the page 
I have the following error 

````
TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at proto.scrollToElement (https://www.wecook.fr/assets/lib/angular-scroll/angular-scroll.js:136:48)
    at Scope.$scope.scrollOnClick (https://www.wecook.fr/assets/js/wecook.controllers.ng.js:75:19)
    at new <anonymous> (https://www.wecook.fr/assets/js/wecook.controllers.ng.js:80:16)
    at Object.invoke (https://www.wecook.fr/assets/lib/angular/angular.js:4169:17)
    at extend.instance (https://www.wecook.fr/assets/lib/angular/angular.js:8422:21)
    at https://www.wecook.fr/assets/lib/angular/angular.js:7677:13
    at forEach (https://www.wecook.fr/assets/lib/angular/angular.js:330:20)
    at nodeLinkFn (https://www.wecook.fr/assets/lib/angular/angular.js:7676:11)
    at compositeLinkFn (https://www.wecook.fr/assets/lib/angular/angular.js:7062:13)
    at compositeLinkFn (https://www.wecook.fr/assets/lib/angular/angular.js:7065:13)angular.js:11562 (anonymous function)
````

in the code 
````
proto.scrollToElement = function(target, offset, duration, easing) {
    var el = unwrap(this);
    if(!angular.isNumber(offset) || isNaN(offset)) {
      offset = duScrollOffset;
    }
    var top = this.scrollTop() + unwrap(target).getBoundingClientRect().top - offset;
    if(isElement(el)) {
      top -= el.getBoundingClientRect().top;
    }
    return this.scrollTo(0, top, duration, easing);
  };
````
when the target is empty getBoundingClientRect() is not working thus in my case causing a crash of my angular app. 

I will make  a test in my code in order to call your function only if the target element exist. 
in this code. 

````
/**
     * @ngdoc function
     * @name
     * @description Scroll the the hash Id
     * we needed this function as normal hash browsing is difficult
     * to make with angular, so a function can help
     */
    $scope.scrollOnClick = function(hashId) {
        var defaultYOffset = 50; // 50 pixel offset from the has destination
        var defaultDuration = 1000; // 1s
        var elementToScroll = angular.element("#" + hashId);
        $log.debug('we want to scroll to ', elementToScroll);

        $location.hash(hashId);
        $document.scrollToElement(elementToScroll, defaultYOffset, defaultDuration);
    };
````

But per aps it's necessary to handle this case for you

**Comment by oblador** [comment]
Do you want it to fail silently or throw a different error?

**Comment by sinsunsan** [comment]
I want it not to crash the whole angular application, would be nice to have an error message though, but it's not the more important. 
The problem in my case is that if I use a hash tag that doesn't exist, it crash my page. 
It's very easy to have a hashtag accidentally added to the url. 
And anyway, I don't want to have urls, where my application crash, because the display is then ugly. 

Is it possible to handle the inexistence of the target in a clean way, so that the angular application didn't crash.

**Comment by samuelbeek** [comment]
Is it possible to somehow block this error? I have the same thing during page load, but don't want my log to get all red.

**Comment by oblador** [comment]
IMHO this *should* throw an exception since you're passing bad arguments. The easiest way for you to not get exceptions is to do your own sanity check of the `elementToScroll` variable. 

The directives will use a fallback and not throw any exceptions, but if you call the API then yes you need to send proper stuff :-) You could argue that the exception itself could be better though.

**Comment by oblador** [comment]
Also, you could wrap it in a try/catch block. Closing for now, feel free to reopen if you want another more informative error message.

**Comment by samuelbeek** [comment]
Your totally right. In the end I created a static include directive instead of using ng-include. This way I didn't get the error on page load.
