### ISSUE TITLE
[bug] hover link after scroll when it is not really hover

### ISSUE THREAD

**Issue by kwladyka** [oblador/angular-scroll#104]
As an screen below when i click on the link it works and scroll down me to right place. But when i scroll up again i see <a> element still has :hover CSS.

![untitled](https://cloud.githubusercontent.com/assets/3903726/5904308/e167f3d2-a587-11e4-8d00-e10b4b5830b3.png)

My code:
```
<a href="#map" class="text-muted" du-smooth-scroll><span class="glyphicon glyphicon-map-marker"></span> Warszawa, Wola, ul. Jana Kazimierza</a>
```

and
```
					<div class="row">
						<div class="col-sm-12" id="map">
							Mapa będzie jak zrobię
						</div>
					</div>
```

**Comment by oblador** [comment]
Pretty sure this has nothing to do with this module :-) Do you perhaps have any `:focus`/`:active` pseudo classes on your links?

**Comment by kwladyka** [comment]
No and it is NOT happen when i use:
```		$scope.gotoMap = function() {
			 $location.hash('map');
			 $anchorScroll();
		};
```

**Comment by kwladyka** [comment]
Oh and i believe it is import: i was testing this on chrome.

**Comment by oblador** [comment]
Can you post a minimal example on plunker with css?

**Comment by kwladyka** [comment]
Can be page?
http://wladyka.eu/a/#/show-offer

click on "Warszawa, Wola, ul. Jana Kazimierza"

**Comment by oblador** [comment]
Just like I wrote earlier your `a:focus` is the problem not this directive. 

This is the culprit:
```css
a:hover, a:focus {
color: #23527c;
text-decoration: underline;
}
```

**Comment by kwladyka** [comment]
But it is default bootstrap twitter CSS settings, not my own custom. Your plugin doesn't work with bootstrap twitter by default?

**Comment by oblador** [comment]
This module is about scrolling and from what I can tell it scrolls just fine. You complain about presentational stuff in bootstrap. Fix your css or file an issue there is my suggestion.

**Comment by kwladyka** [comment]
So it is not about method used in your module? $anchorScroll(); works good so it makes me a little confuse.

Can you also give me a hint how did you debug that? In chrome inspect element i don't see :fous on this element.

PS Thx for help.

**Comment by oblador** [comment]
Because your other example didn't have a `href`-attribute is my guess. You can force `:focus`-state in chrome inspector by right clicking it.

**Comment by kwladyka** [comment]
Oh in that way... thx.
