### ISSUE TITLE
Scroll to anchor from controller (du-scroll-container approach)

### ISSUE THREAD

**Issue by nirium** [oblador/angular-scroll#105]
Hi,

I have a problem. When testing with <a> links it works as expected. I have a du-scroll-container and when I click a <a> element with an anchor it scrolls to it (using du-smooth-scroll). The scroll-container then scrolls to the appropriate cell.

How do I do this through a function in the controller? I pass the id as a parameter and tried to use "container.scrollToElement(anchor, 0, 800);" but I'm getting "el is undefined".

The full function looks like this (called through ng-click):

	$scope.scrollToMatch = function(match) {
		var anchor = "#" + match.id;
	    var container = angular.element(document.getElementById('scroll-container'));
	    container.scrollToElement(anchor, 0, 800);
	}

Any ideas?

Thanks in advance!

**Comment by oblador** [comment]
`anchor` should be an element instead of a css-identifier. Try using `var anchor =  document.getElementById(match.id);` instead (or maybe `anchor = match;` depending on what match is).

**Comment by nirium** [comment]
$scope.scrollToMatch = function(match) {
		var anchor = document.getElementById(match.id);
		console.log(anchor);
	    var container = angular.element(document.getElementById('scroll-container'));
	    container.scrollToElement(anchor, 0, 800);
	    container.on('scroll', function() {
	      console.log('Container scrolled to ', container.scrollLeft(), container.scrollTop());
	    });
	}

Still gives "el is undefined". The console output of anchor results in:

 <div id="5203575273684992" class="tournament-container ng-scope" ng-class="tournament.isExpanded ? 'expanded' : ''" ng-repeat="tournament in tournaments.sections[0].finished" du-smooth-scroll="" ng-attr-id="{{tournament.id}}" style="">

Seems like it's the element alright. 

Thanks for fast reply!

**Comment by nirium** [comment]
Managed to find the issue. I was actually missing an id on the scroll-container. Thought you did some magic when assign "scroll-container" to the du-scroll-container directive but it actually required me to set an id to that element

**Comment by oblador** [comment]
And if you log `document.getElementById('scroll-container')`?

If you use the latest non minified version, on what line is it throwing the error?
