### ISSUE TITLE
angular-scroll not working when triggered by touch event

### ISSUE THREAD

**Issue by yjaaidi** [oblador/angular-scroll#106]
Hi,

We are using angular-scroll on our gift ideas & wishlist service https://www.wishtack.com.

But the problem is that we think that we noticed a bug on mobile devices. We trigger the scroll using an 'ng-click' but the touch event also cancels the scroll before it can't really start.

This happens in 'cancelScrollAnimation' where you have this condition '$event.which > 0' but the touch event '$event.which' is set to 1. Maybe, the condition should be more restrictive?

Thanks in advance and thank you by the way for this great module.

Younes
for Wishtack.com

**Comment by oblador** [comment]
Hi, 

Had a hard time finding where on the site the bug appears, can you point me in the right direction?

Anyway, does it solve your problem if you replace the condition you are referring to with the following?
```js 
if (!$event || (startTime && $event.which > 0)) {
```

**Comment by panstav** [comment]
Having this issue with my mobile device, although $event.which is undefined, probably because I call `scrollToAnimated()`.

But animation doesn't happen, it just scrolls to, normally.

**Comment by oblador** [comment]
@yjaaidi & @panstav : Did you try my proposed solution?

**Comment by yjaaidi** [comment]
Hi Joel, sorry but we are still not using angular-scroll on production.
That's why you couldn't find it :)

I'm gonna try your solution right now!

**Comment by yjaaidi** [comment]
Well, it still doesn't work as the scroll is canceled during the first
animation step so 'startTime' is initialized.

But, when I moved 'progress' variable declaration to 'duScrollToAnimated'
and using it in the condition it works with:

*if (!$event || (progress && $event.which > 0) {*

Is it an acceptable solution?

Thnaks!

**Comment by panstav** [comment]
@oblador, yea, what I meant by my previous comment was that I did try your solution - with no results.

I believe it is because I used that method - `scrollToAnimated()`, so that `$event.which` doesn't get populated with click / touch, and a beacon I've set inside the event cancellation function doesn't get called at all.

**Comment by panstav** [comment]
UPDATE: It actually IS working for me, trying it out on different devices - I found out the animation was just a bit too fast to notice, which is exactly why I needed the module - to make sure user understands he's just a scroll away from where he previously been.

Tried different duration times, I now have a great effect working on both desktop and mobile.

Thanks!

**Comment by oblador** [comment]
@yjaaidi: used your solution but don't really get why they should differ since they are populated in the same function call :-)

**Comment by yjaaidi** [comment]
Great! Thanks!

Actually it doesn't work with 'startTime' because on the first call to
`animationStep`, 'startTime' is initialized to 'timestamp' and progress is
initialized to 'timestamp - startTime' which is equal to 0 on the first
call. So 'progress' will only get greater to 0 at the second call ;)

By the way, when are you planning to release the 0.6.5 with this fix?

Thank you again!

Younes
for https://www.wishtack.com

**Comment by oblador** [comment]
Here's [0.6.5](https://github.com/oblador/angular-scroll/releases/tag/v0.6.5)!

**Comment by yjaaidi** [comment]
Super! Thanks!
