### ISSUE TITLE
Using the plugin without the #

### ISSUE THREAD

**Issue by yahyazini** [oblador/angular-scroll#111]
First of all thank you so much for this great piece of code.

I have trouble using the plugin with Angular Ui-Router and it's mainly due to the fact that it uses href and #something... so my router tries to redirect instead of executing the directive code.

Is there a way to avoid that?

Cheers!

**Comment by Reeebuuk** [comment]
Have the same issue...

**Comment by redben** [comment]
Expected. Especially when code $anchorScroll has that. It would be a great addition.

**Comment by oblador** [comment]
Support for using the `du-smooth-scroll="your-id"` instead made it into [0.7.0](https://github.com/oblador/angular-scroll/releases/tag/v0.7.0).

**Comment by achristie** [comment]
does this allow using the module with ui-router? a simple use case for me isn't working and i have no idea why.

the nav
```
ul.nav.nav-pills.nav-stacked
    li(ng-repeat='c in description.Components')
        a(du-smooth-scroll='{{c.Name}}', du-scrollspy='') {{::c.Name}}
```
the table
```
div(ng-repeat='component in description.Components', ng-attr-name='{{component.Name}}')
	h4 {{::component.Name}}
```

**Comment by oblador** [comment]
@achristie: The scrollspy will have problems with dynamically created elements, but smooth scroll should work. Did you try to use `id` or `name` instead of `ng-attr-name`?

**Comment by achristie** [comment]
@oblador: Thanks for reply. I did try variations including what you suggested but no luck. I've also tried programmatically calling scrollTo and again no luck.

**Comment by oblador** [comment]
@achristie: OK, can you post this as a new issue with a minimal plunker?
