### ISSUE TITLE
Issue with duScrollspy:becameActive, something is watching $location.hash() 

### ISSUE THREAD

**Issue by smysnk** [oblador/angular-scroll#112]
This is not necessary an issue with angular-scroll spy but I am posting this here, maybe somebody can give me some suggestions on where to look to solve my issue.

I am using the duScrollspy:becameActive code example from the angular-scroll readme example under events.  

The behaviour that I am seeing is the location hash is changing properly as different sections become active when scrolling down the page; however, when scrolling back up the page as soon as a new section is reached and the URL hash is changed it will jump scroll to the top of the section.

This leads me to believe something is watching the location hash and triggering off of the duScrollspy:becameActive handler, when we call '$location.hash(hash.substr(1)).replace();'

Things I have tried:
- Disabling [anchorScrollProvider. disableAutoScrolling()](https://docs.angularjs.org/api/ng/provider/$anchorScrollProvider)

Other modules I am using that might be responsible:
- angular-ui-router

Anyone experience this before or have any suggestions as to where I should be looking to identify the culprit?

Thanks!

**Comment by oblador** [comment]
Hi, sorry for super late reply. Could you post a minimal plunker for me to debug?

**Comment by MartelBenjamin** [comment]
Hi, i have the same problem but i can't create a plunker because we have to use a base like this : ` <base href="/">` and they can't link the javascript to the html and we don't know it ^^.
http://plnkr.co/edit/8Peerf3jZDbOFdQmmUZj?p=preview

**Comment by oblador** [comment]
@MartelBenjamin: Maybe you can create a locally working example and put it on dropbox as a ZIP-file instead?

**Comment by smysnk** [comment]
I revised MartelBenjamin version: http://plnkr.co/edit/aDTLBICDtPoHXbvoKEgK

**Comment by oblador** [comment]
Thanks, that helped me solve the problem!

Somehow the `$location` API is not using the `history` API to update the hash, so I've updated the readme with the following example which doesn't use it:

```
angular.module('myApp', ['duScroll']).
  run(function($rootScope, $location) {
    if(!history || !history.replaceState) {
      return;
    }
    $rootScope.$on('duScrollspy:becameActive', function($event, $element){
      //Automaticly update location
      var hash = $element.prop('hash');
      if (hash) {
        history.replaceState(null, null, hash);
      }
    });
  });
```

**Comment by smysnk** [comment]
Sorry, where does the history variable come from?

**Comment by oblador** [comment]
https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history

**Comment by smysnk** [comment]
oooooh.  Thanks for answering my silly question.

**Comment by kukac7** [comment]
@oblador `console.log(hash);` undefined

**Comment by mebibou** [comment]
I have another bug related to this: I am using the code provided in the README, however when I click on something in the page that is handled by a `ng-click` (like `<div ng-click="doSomething()">`), the page will jump to the section which is linked to the last state that was replaced. Basically the steps are:

1. Scroll manually to a section that is "spied"
2. The code provided will kick in and the state will be replaced
3. Scroll down a bit more in the same section (so the state won't change)
4. Click on anything that has a `ng-click` on it
5. The page will jump back to the top of the section

Again, not caused by this library but maybe someone has faced this issue and solved it already (

**Comment by alexxdim94** [comment]
@mebibou Have you found a solution to the issue? I've been trying to fix that for the last few days and it's killing me inside ... 😆

**Comment by mebibou** [comment]
@alexxdim94 I don't remember exactly what I did, but I think I had to remove the library and do it another way. So didn't find a solution

**Comment by Akeri** [comment]
Hi. I know, bit late but just faced this issue.
If you are using ui-router, handle duScrollspy:becameActive like this:

```javascript
$rootScope.$on('duScrollspy:becameActive', function ($event, $element, $target) {
    $state.params['#'] = $element.prop('hash').replace('#', '');
    $state.transitionTo($state.current.name, $state.params, {notify: false, replace: true});
});
```

This means you are replacing the location hash via ui-router $state service.
This way, ui-router healthy tracks the history and won't fail at a state change.
