### ISSUE TITLE
Event cancellation option

### ISSUE THREAD

**Issue by njakob** [oblador/angular-scroll#114]
By using `scrollToElementAnimated()`, due to #49, some events cancel the animation. Would it be possible to add this cancellation feature as an option?

**Comment by oblador** [comment]
Don't want to make *everything* into an option, but if you have a solid usecase then sure :-)

**Comment by njakob** [comment]
I encountered this issue when the animation is fired by a scroll event itself in order to create a smooth scroll between some sections of a page (as currently implemented on http://wicard.ch).

Because of this auto-cancellation, if the user scroll twice, the animation is simply stopped in the middle of two elements and I found nothing to prevent that.

**Comment by szabyg** [comment]
We use this component to transition between "desktops". There's a keyboard shortcut and a button for switching between them. A state between two of these desktops looks broken. Therefore we need this option.

**Comment by ftorghele** [comment]
+1

**Comment by iradovanovic** [comment]
One more here.

**Comment by TGVarik** [comment]
+1, or expose the list of events that cancel the scroll so it can be modified at runtime.

**Comment by oblador** [comment]
@TGVarik: That sounds like a reasonable way to do it.

**Comment by oblador** [comment]
Added the `duScrollCancelOnEvents` option in https://github.com/oblador/angular-scroll/commit/2b54fae160089b51b4e076325f86a00769d9a479

Check out the repo, build via `gulp compress` and check if it solves your problems. If so I'll publish it shortly.

**Comment by TGVarik** [comment]
Yes. Glorious. That works for us!

**Comment by oblador** [comment]
It's available in [0.7.1](https://github.com/oblador/angular-scroll/releases/tag/v0.7.1)!
