### ISSUE TITLE
Multiple directives [modalWindow, duScrollContainer] asking for new/isolated scope

### ISSUE THREAD

**Issue by guncha** [oblador/angular-scroll#115]
It looks like `duScrollContainer` directive is creating a new isolate scope just to register a callback when it gets destroyed. This prevents it from being used on an element with another directive that creates a scope (modalWindow in my case). Can't the same effect be achieved using `element.on("$destroy",...)`?

**Comment by oblador** [comment]
The scope is used to associate scrollContainer by inheritance. It would be possible to do the same using the DOM I guess, but it would make it slower and require a quite big refactor.
