### ISSUE TITLE
Scrolling within a div with overflow: scroll/auto

### ISSUE THREAD

**Issue by ericodes** [oblador/angular-scroll#116]
It looks like you can use the Scroll API and pass an element to scroll to its position. 

Is it possible to scroll to a specified position within a specific element (that has overflow: scroll or overflow: auto) instead of scrolling $document?

**Comment by oblador** [comment]
Yes, just replace `$document` with your `angular.element` wrapped element. See [demo](http://oblador.github.io/angular-scroll/container.html).

**Comment by ericodes** [comment]
Got it, had forgotten to angular.element wrap the element. Thanks for your prompt help! And a huge thank you for sharing this directive :) It's so robust and well thought out.
