### ISSUE TITLE
du-scrollspy is not working on two elements targeting the same div

### ISSUE THREAD

**Issue by deepsaurabh** [oblador/angular-scroll#119]
I have two elements one anchor tag and other button that targets same div. 
I want the active class to be added on anchor element.
But  on every refresh of the page some times it is adding active on anchor element and sometimes it is adding active on button element

**Comment by oblador** [comment]
You'll need to wrap it with a [`du-scroll-context`](https://github.com/oblador/angular-scroll#du-spy-context) to make that work.

**Comment by deepsaurabh** [comment]
Wrap both the elements in du-scroll-context or the one inside ``` <ul></ul>``` tag ???

**Comment by oblador** [comment]
Please read the manual that I linked to.

**Comment by deepsaurabh** [comment]
It worked. Thanks
