### ISSUE TITLE
Request: Add du-scroll-delay

### ISSUE THREAD

**Issue by epelc** [oblador/angular-scroll#120]
Thanks for the great project I've been using it for a while. But I ran into a small issue today when using it with angular-material(however this is general). I want to request a `du-scroll-delay` directive be added so that we can delay the scrolling for x milliseconds. I need this so that I can wait for a dialog to close before scrolling otherwise there are big jumps if your dialog is animated. I don't think this is specific to angular-material so I thought it'd be a good feature. Let me know your thoughts.

**Comment by oblador** [comment]
Hi! You can use `$timeout` and then `$document.scrollToElementAnimated`. A directive just for this seems to be a bit too specific imho.

**Comment by epelc** [comment]
Thanks I think I'll do that.
