### ISSUE TITLE
Is that possible to scroll to bottom/top by 1/3 screen?

### ISSUE THREAD

**Issue by Perpherior** [oblador/angular-scroll#121]
Now I have a page that get article content from database, which means it is hard to set anchor inside the content.
The dom structure like this:
```
<nav></nav
<pre>{{article.content}}<pre>
<footer />
```
 I hope I after I press space/down key, the page scroll to bottom by, maybe, 1/3 of screen. In other word, the scroll function should override browser's one.  Is it possible to do so?

**Comment by oblador** [comment]
In theory you could use `$document.scrollTopAnimated` on a keydown event and then `event.preventDefault()`.

**Comment by Perpherior** [comment]
Thanks for your reply. This solves part of my problem. It seems the offset of scrollTop function is based on top of the page. But I cannot guarantee every client only use keydown at the top. So is that any function could return current offset ?
