### ISSUE TITLE
animation is called by scrollTo but nothing moves

### ISSUE THREAD

**Issue by rjwalters** [oblador/angular-scroll#123]
I'm having a lot of trouble getting angular-scroll to work so I thought I would see if there's something obvious that I'm doing wrong. I've added a bunch of print statements to try to track down the problem:

(setup on load)
returning polyfill function
angular-scroll.js:209 polyfill returns: function cancelAnimationFrame() { [native code] }
angular-scroll.js:207 returning polyfill function
angular-scroll.js:209 polyfill returns: function requestAnimationFrame() { [native code] }
(...click to scroll)
ctrl.home.js:15 calling scrollTo
angular-scroll.js:149 scroll to element calculates: 612.5347290039062
angular-scroll.js:72 scroll to animated called with: 0,612.5347290039062,600,undefined
angular-scroll.js:134 requesting an animation
ctrl.home.js:16 done with scrollTo

It appears that everything is happening as it should, but nothing happens visually. I am able to use the $anchorScroll directive to move around without animation. I replaced all the html in my partial with the content of the example and turned off my css and the problem persists.

Is there something else I can test to see what is going wrong?

Are any of these libraries suspect:

angular.min.js
firebase.js
angularfire.min.js
angular-route.min.js
ui-bootstrap-tpls-0.13.0.min.js
angular-promise-extras.js
hammer.min.js 
gestures.min.js
angular-sanitize.min.js
angular-scroll.js
angular-payments.min.js

Thanks.

**Comment by oblador** [comment]
I don't think it's a bug and it's very hard for me to tell what the problem is with so many libraries that could potentially interfere and no example code. Can you create a minimal reproducible example and put it up on plunker so I can investigate further?

**Comment by rjwalters** [comment]
Thanks for your note... so far all of my minimal examples are still working, but I'll keep at it. 

Any thoughts on whether it's more likely to be a css issue or something else?

**Comment by rjwalters** [comment]
I think I must be setting up the container incorrectly, because the document method is now working for me...

This works fine:
		$scope.scrollToAnchor = function(id) {
			var target = angular.element(document.getElementById(id));
			console.log("calling scrollTo")
			$document.scrollToElementAnimated(target)
				.then(function(){console.log("done with scrollTo");});
		};

This has no effect:
		$scope.scrollToAnchor = function(id) {
			var target = angular.element(document.getElementById(id));
			var container = angular.element(document.getElementById('container'));
			console.log("calling scrollTo")
			container.scrollTo(target, 70, 600)
				.then(function(){console.log("done with scrollTo");});
		};

**Comment by oblador** [comment]
The difference in the two is that one is scrolling the window and the second is scrolling just a container element. If it doesn't work, they I'm guessing your missing either a fixed height or `overflow: auto;`. Again without more code it's impossible to say, what you posted so far looks correct.

**Comment by rjwalters** [comment]
I tracked down the problem to css:

#container {
  overflow: auto;
  height: 1800px;
}

Both attributes must be set for the scrolling to work. Maybe this obvious to everybody but me... or potentially worth a comment in the example code?

http://plnkr.co/edit/KYWlsMQIZkI8ZMtP7ET1 

I'm happy with scrolling with the document technique as an alternative so my issue is solved.
