### ISSUE TITLE
Link doesn't load the page with the script duScrollspy:becameActive

### ISSUE THREAD

**Issue by MartelBenjamin** [oblador/angular-scroll#124]
This script works well but I discovered that the links to another page doesn't work. The url changed but not the content.

This is the plunker with the script and so the page doesn't load : http://plnkr.co/edit/emrTAvTPMKbLUNYi40Xq?p=preview

And the plunker without the script, the page load : 
http://plnkr.co/edit/xfsAWsLADkW6F98exC4P?p=preview

**Comment by MartelBenjamin** [comment]
With the new script it's works perfectly ;) Thanks :D

**Comment by oblador** [comment]
Was just about to write about it haha.

**Comment by MartelBenjamin** [comment]
Yes thanks ^^
