### ISSUE TITLE
Comments in minifiy file

### ISSUE THREAD

**Issue by QuentinBontemps** [oblador/angular-scroll#126]
I use your file, and i would like contact all angular plugins in one file, but in your minify file you added a commentary. Can you replace "//" by "/* */" ?
Thank you.

**Comment by oblador** [comment]
If you're concatenating and minifying your dependencies into a single file you should not use the minified version, but the development version. Also you should not keep source map comments since they don't make sense anymore.

**Comment by QuentinBontemps** [comment]
Ok, thank you for your quick reply.
