### ISSUE TITLE
scope variable for element being active

### ISSUE THREAD

**Issue by episodeyang** [oblador/angular-scroll#133]
Hi,

I am trying to use the element.active state as trigger for another directive. Is there a way to access this state parameter in the scope of the element? This could be very useful if it become a standard part of the API.

Best,
Ge

**Comment by oblador** [comment]
This should be doable using [`duScrollspy:becameActive` events](https://github.com/oblador/angular-scroll#events).

**Comment by episodeyang** [comment]
Thanks! Ended up doing that.
