### ISSUE TITLE
scroll does not when if element is empty

### ISSUE THREAD

**Issue by episodeyang** [oblador/angular-scroll#134]
I am trying to animate some block. The block is empty until it is in view, to let the content appear gradually. 

I suspect this has something to do with the fact that angular-scroll uses range selection. the selection is null when the block is empty. A `<br>` node or some better handling is needed.

Ge

**Comment by oblador** [comment]
Hi @episodeyang, I'm sorry but I don't really follow :-( Can you try to rephrase or demonstrate with a plunker?

**Comment by episodeyang** [comment]
Hi, 

Sorry for this late reply! 

The issue is that when the element we try to scroll to is a block element and it is empty, the angular-scroll directive does not properly scroll  to that element. 

And this might have something to do with how angular-scroll uses range selection to find the particular element. 

This was a few month ago so I don't remember. If this sound confusing please just ignore it.

Thanks for this library!

Ge
