### ISSUE TITLE
scrollToElement fails

### ISSUE THREAD

**Issue by edamron** [oblador/angular-scroll#140]
Hello!

I'm having a hard time determining why my calls to scrollToElement sometimes work and sometimes don't.  My slimmed down code looks like this ('page' is a var I've confirmed refers to an ID in the DOM, located via "angular.element(...)"):

myViewerDiv.scrollToElement(page, 10, 2000, myEasingFunction).then(function () {
    $log.debug('scrollToElement page "' + page[0].id + '" succeeded');
}, function(reason) {
    $log.debug('scrollToElement page "' + page[0].id + '" failed: ' + reason);
});

When "function() {...}" is called, the element I'm trying to scroll to does in fact scroll into view.  When the second function is called, reason is undefined (which is fine if in fact no reason is provided) and the element I'm after in the DOM is not scrolled into view.

NOTE: I am attempting to scroll to a DIV within another DIV marked as overflow: scroll, but I AM using du-scroll-container per your documentation.

Any idea why it works sometimes and not others??  I'm currently using version 0.6.4.

Thanks!

**Comment by edamron** [comment]
BTW, I just noticed that if I navigate to the page on which the above code operates, and once the page loads on its own, I press CMD-R to reload the page, it ALWAYS works from there on out.

HTH

**Comment by edamron** [comment]
Sorry to add yet another comment, but I did just update to version 0.7.1, to eliminate that as a possibility.

Thanks again!

**Comment by oblador** [comment]
Are you sure page is defined? Will multiple calls sometimes work? Are you scrolling the page manually at the same time (this will cancel the scroll)?

**Comment by edamron** [comment]
One thing that's handy is that I can absolutely repeat the issue with a certain sequence of events with my app.

When it doesn't work, I have used Chrome to 'inspect element', and scrolled down through the HTML to ensure an IMG with the ID I'm scrolling to exists.  It does.

As for multiple calls, that doesn't seem to work either.  If my ng-repeat emits 20 images, and I have 20 corresponding links that, when clicked, attempt to scroll, what ends up happening is it scrolls a little closer each time, but it takes sometimes 5 or six calls to get all the way down the page.

As for scrolling, not intentionally.  COULD there be something causing that...I suppose.  Since I'm scrolling down to one of 17 IMG tags (in my current test case), I've tried waiting to ensure all images are loaded prior to attempting to click on the DIV that would trigger the scroll.

Any places I could set a breakpoint perhaps and compare values when it works vs. doesn't??

Thanks

**Comment by edamron** [comment]
Hmmm...just noticed something that may allow me to move on without figuring this out...

My page is basically laid out with a repeat over an array of documents, with each page image being placed into an IMG tag.  Right next to the array of page images is a bootstrap accordion, with page thumbnails that can be clicked on to 'angular-scroll' down to the appropriate full-size page image.

As the large images scroll, I also have events that fire which cause the accordion thumbnails to scroll.  This functionality is used to keep the accordion in sync with the user, should they choose to simply scroll down through the list of full-sized page images with their mouse wheel (or trackpad on a Mac).

I have one call to scrollToElement inside the ".then" of the other one.  I thought the main scroll would be completely done before entering the ".then", but perhaps not.  Perhaps THAT is the other scroll going on at the same time that's causing the other one to stop??

Thanks!

**Comment by edamron** [comment]
I think your suggestion of multiple scrolls going on simultaneously is what's going on.  as the user scrolls through the large images, the accordion is also scrolling to try to stay in sync.  The same can also be true in the opposite direction (the large images scrolling based on a different thumbnail selection).

I'm thinking my code must have overlapping calls to scroll, in which one scroll stops the other.  Investigating further...

**Comment by edamron** [comment]
Pretty sure it's just competing scrooTo's...you can close this.

Thanks very much.
