### ISSUE TITLE
Issues with using custom containers

### ISSUE THREAD

**Issue by gandrews-netfore** [oblador/angular-scroll#141]
given the below - adjusted from the example the scroll does not behave as expected.

The first link to section-1 does nothing (id="section-1" exists in adjacent div)
The second link to section-2 works but jumps there but does not animate.
```
<div du-scroll-container="div-scroll">
  <nav>
    <ul>
      <li><a href="#section-1" du-smooth-scroll du-scrollspy>Section 1</a></li>
      <li><a href="#section-2" du-scrollspy>Section 2</a></li>
      <li><a du-smooth-scroll="section-3" du-scrollspy>Section 3</a></li>
      <li><a href="http://github.com/oblador/angular-scroll/">Project on Github</a></li>
    </ul>
  </nav>
</div>
<div id="div-scroll">
....
</div>
```

**Comment by oblador** [comment]
Your example is incomplete, but I'm guessing you haven't added appropriate styling to the `#div-scroll` element. Can you post a plunker for me to examine? Does the [demo](http://oblador.github.io/angular-scroll/container.html) work?

**Comment by gandrews-netfore** [comment]
Many thanks for the response.  Yes the demo works – and after some additional investigation it appears to be an issue with using href=”#...” and uirouter.  I attempted to handle the click in the controller eg. Using scrollTo but this still leads to the address / location being modified which uirouter is observing.  Any experience in dealing with this conflict?

**Comment by oblador** [comment]
Ah, just use the `du-smooth-scroll` attribute instead of `href="#…"`.

**Comment by gandrews-netfore** [comment]
Yes thanks Joel I tried that as it was documented in your detailed notes for the project.  I could be wrong but doesn’t this still simply call scrollTo etc eventually that leads to modifying the location, hence uirouter gets involved again.  Here is the link I have tried – below inside of ng-repeat.

<a href="javascript:void(0)" du-smooth-scroll="{{item.anchor}}" du-scrollspy>{{item.label}}</a>

I also tried using <li> and handling ng-click and calling container.scrollTo(id) in the controller – no luck.

I appreciate your suggestions Joel.  Many thanks.

**Comment by oblador** [comment]
Not a user of uirouter myself, but try skipping `href` entirely like this: `<a du-smooth-scroll="{{item.anchor}}" du-scrollspy>{{item.label}}</a>`. Also `item.anchor` should not include the hash.

**Comment by gandrews-netfore** [comment]
I was able to get this working in the end.  The scrollable area did not correspond to the container id I had provided.  I had to rework the layout such that the correct child was scrollable.  I also needed to do what Joel had mentioned above.
