### ISSUE TITLE
UI-Sref redirects to anchor instead of parent state

### ISSUE THREAD

**Issue by AssassinsMod** [oblador/angular-scroll#143]
It seems like adding to history the anchor causes, at least for me, an error while switching to a parent state.

```javascript
$rootScope.$on('duScrollspy:becameActive', function (event, $element) {
    if ($element.prop('hash')) {
        history.replaceState(null, null, $element.prop('hash'));
    }
});
```

Having `parent` and `parent.child` states, while being in the child state and having the hash in the url (in my case `#/test/forge#download`), clicking on a `<a ui-sref="parent"...`, (external to the view) instead of switching to parent state, it scrolls to the `#download` anchor.

On the other hand if the url doesn't have any hash (again ``#/test/forge`), the ui-sref works just fine..

(I didn't look deeply into this nor to make a plunker, as soon as I have some time i'll make one)

![Angular 1.4.5](https://img.shields.io/badge/Angular-1.4.5-green.svg)
![Scroll 0.7.2](https://img.shields.io/badge/Scroll-1.7.2-green.svg)
![UI Router 0.2.15](https://img.shields.io/badge/UI--Router-0.2.15-green.svg)

**Comment by oblador** [comment]
Hi, I'm not sure I understand exactly (a plunker would be greatly appreciated :-), but having multiple hashes in your url is not a good idea.

**Comment by AssassinsMod** [comment]
Due to having lost all my data I am not able to provide you an example.
Anyway I agree that having multiple hashes is not a good idea.
