### ISSUE TITLE
How to add parent ul menu active class

### ISSUE THREAD

**Issue by hugsbrugs** [oblador/angular-scroll#148]
Hi there and thanks for your great plugin !

I would like to be able to create a page with same sidebar than in bootstrap website docs using your module mainly because it does not rely on jquery ...

I've created a sample case [codepen](http://codepen.io/hugsbrugs/pen/vNKQPV) where almost everything works as expected unless sub menus. The fact is that parent li looses active class when it's child li acquires this same active class ! I need the two of them to get active class. I've tried to play around with du-spy-context with no luck.

I would appreciate any ideas or suggestions about how to achieve this functionality (if we're able to make it, I'm sure this would make a good other sample page ! ;) )

Hugo

**Comment by oblador** [comment]
Have you tried the setting [duScrollGreedy](https://github.com/durated/angular-scroll#greedy-option) to true?

**Comment by hugsbrugs** [comment]
Updated [codepen](http://codepen.io/hugsbrugs/pen/vNKQPV) with no more luck. Does this option plays with other options ? Thanks !

**Comment by hugsbrugs** [comment]
Resolved thanks to this one : https://github.com/oblador/angular-scroll/issues/108

I was missing the : 
```javascript
du-spy-context="section-4"
```
it works with or without : 
```javascript
.value('duScrollGreedy', true)
```
Last thing to make it perfect, I've added : 
```javascript
.value('duScrollBottomSpy', true)
```
but it doesn't seem to work. Do you think this is because of sub element ? 

Thanks very much for you quick answer !

**Comment by oblador** [comment]
I don't think `duScrollBottomSpy` works very well with multiple contexts I'm afraid :-/

**Comment by oblador** [comment]
Realized just now, there's already a [TOC sample page](https://github.com/oblador/angular-scroll/blob/master/example/toc.html) :-)
