### ISSUE TITLE
Is it possible to spy on a section that has no link to that section ?

### ISSUE THREAD

**Issue by daniboomerang** [oblador/angular-scroll#153]
Hi,
Sometimes the need to spy something is just to trigger animations or something else but there is actually no link to go to the section

In those cases it is quite ugly to add an `<a href>` like this to be able to spy on my-section:

`<a href="#my-section" du-scrollspy></a>
 <div id="my-section">
  ....
 </div>`

Is there a way to spy a section without an `<a href>` element?

Thanks, regards and congratulations for your directive. It´s been very useful to me.

Dani

**Comment by oblador** [comment]
Hi, 

Yes as the [documentation states](https://github.com/oblador/angular-scroll#du-scrollspy) you can simply pass the id in the attribute like this: `<a du-scrollspy="my-section">`. Of course you can use another element than `<a>` if that makes more sense in your code :-)

**Comment by daniboomerang** [comment]
Thank you very much for your quick answer.
That´s what I needed to know

Regards
