### ISSUE TITLE
duScrollBottomSpy issue with document.body.scrollHeight on IE11

### ISSUE THREAD

**Issue by jrr** [oblador/angular-scroll#160]
We encountered an issue where under IE11, the last item in our nav was "stuck" on. Under certain circumstances, IE11 will report `document.body.scrollHeight` of zero, causing `bottomReached` to always be true in the scroll handler.

Specifically I'm seeing it with IE 11.0.9600.18059 and Angular 1.4.7.

Repro with this plunk: http://embed.plnkr.co/xKx6ATH1jtBVr2FcOeNO/preview

Pull request that fixes it: https://github.com/oblador/angular-scroll/pull/157

**Comment by oblador** [comment]
PR was merged.
