### ISSUE TITLE
scrollLeft not working when attempting to fire on multiple elements in series

### ISSUE THREAD

**Issue by Duder-onomy** [oblador/angular-scroll#169]
Hi, 
Found this issue. 

If I have 2 identical elements in DOM, and I use the `scrollLeft` method to scroll them. Only the last one ever scrolls, though, I can confirm the scrollLeft is being called on them correctly. 

Please look at this fiddle to see the issue: http://jsfiddle.net/hhofs63a/
I tried to boil it down to the simplest possible example. 
Observe that only the second panel will scroll. 

Thanks
Greg

**Comment by oblador** [comment]
Hi @Duder-onomy, 

Yes unfortunately triggering a scroll animation will cause the current one to be cancelled. This is a rest from when this component would only scroll the browser window. I'll happily accept a PR fixing this issue by cancelling scrolls by container.

**Comment by Duder-onomy** [comment]
Dang, 
Thanks @oblador. That is a bummer.

In my actual use case, only one panel is actually shown at once, but I need to keep them [in sync](http://www.nsync.com/). So I will animate the one showing, then just use the native scrollLeft on the one that is hidden. 

I would make a PR...but I have no idea how you pulled this off. Haha, and its my first angular app. so, unfamiliar with all the moving parts. 

I will close issue for now. 
Greg

**Comment by alexthewilde** [comment]
@oblador I've encountered the same issue with simultaneous scrolls in multiple containers not working. I'd pay a bounty for a fix ;)
