### ISSUE TITLE
[Request] Define Scroll Container when triggering from controller

### ISSUE THREAD

**Issue by SavePointSam** [oblador/angular-scroll#196]
Currently, there is no way to fire a duScroll event from a controller that scrolls to an element in a modal. This functionality exists using directives, however I want to keep all the logic for my scroll event in my controller as it fires after modal initialization and won't want to fire a click event from the controller to a fake button in the DOM.

**Comment by arashhdr** [comment]
you can do like : 
`
var offset = 30;
var duration = 2000;
var focusElement = angular.element(document).find('#focus-id');
var container = angular.element(document.getElementById('container-id'));
container.scrollToElement(focusElement, offset, duration);
`
