### ISSUE TITLE
[Feature Req.] Activate last element when bottom reached

### ISSUE THREAD

**Issue by tschneid** [oblador/angular-scroll#77]
Hi,
I've come across this issue, since the last section of my website (#contact) is to small to get to be the top element when scrolled to the bottom of the page -- thus, does not get activated in my menu bar (adding a higher offset would interfere with the rest of the page).
So, an enhacement would be to always activate the last spy, when the bottom of the page is reached. As far as I know, this is also the default behaviour in the latest bootstrap scrollspy.js. For angular-scroll this behaviour could be activated with a switch or so.

In `angular.module('duScroll.spyAPI')` you could add

``` js
var bottomReached = ($window.scrollY + $window.innerHeight === $document[0].body.scrollHeight);
if (bottomReached && activateLastSpyOnBottom) {
  spy = spies[spies.length-1];
  toBeActive = {
    spy: spy,
    top: spy.getTargetPosition()
  };
} else {
  for(i = 0; i < spies.length; i++) {
  // ... same as before; pick the correct spy for the current position
  }
}
```

I tested this on Chrome and Firefox and it worked as expected.

**Comment by lawrencealan** [comment]
Is there functionality like this, only for the first element? It never seems to broadcast for me..

**Comment by oblador** [comment]
@lawrencealan: Do you mean like https://github.com/oblador/angular-scroll/issues/128? Then no, PR is welcome :-)
