### ISSUE TITLE
Link spy without hashtag in href

### ISSUE THREAD

**Issue by eventures-io** [oblador/angular-scroll#88]
Hi,

I'm using ui-router and not using hashtags for my links to anchors but a slash. (href="/link")
By adding an a config option it would be easy to support / (or any other prefix maybe) instead of the hashtag.  I've tested this locally and it works fine. If you think it's a useful feature I can create a pull request.

**Comment by oblador** [comment]
This should be possible using the `du-smooth-scroll` attribute instead from #117.
